### ISSUE TITLE
Disable power of two texture import setting by default

### ISSUE THREAD

**Issue by LeXXik** [playcanvas/editor#106]
Forum topic: https://forum.playcanvas.com/t/disable-texture-pot-by-default/13974

There is a suggestion to make the setting off by default.
@yaustar also offered an option for a warning message instead.

**Comment by slimbuck** [comment]
Done

**Comment by Maksims** [comment]
This will lead to unexpected issues where for NPOT textures mipmaps and `repeat` UVs are not supported (WebGL 1). So this will lead to users wandering why their textures look good on some computers, and bad on the others (like iOS currently, as it does not support WebGL 2).

Please, reconsider the change.

**Comment by willeastcott** [comment]
We did give this a lot of consideration. The conclusion was that we shouldn't try and magically transform imported data by default. We no longer recompress PNG/JPG on import. And in the same way, we no longer (by default) resize textures. What you upload is what you get. But if a developer wants to enable this feature, they can opt-in. The WebGL 1 thing is fast becoming less of an issue because WebGL 2 is now enabled on iOS. However, one thing we *could* do is, for non-POT textures with mipmap filter, show a warning in the Inspector that mipmapping will be disabled for WebGL 1 devices.
