### ISSUE TITLE
Capsule collider can't see collider visual 

### ISSUE THREAD

**Issue by utautattaro** [playcanvas/editor#107]
Hi, I can't see collider in editor view port ,when I choose Capsule collider.
![image](https://user-images.githubusercontent.com/7885830/88171532-6d3c1b00-cc5a-11ea-8199-1b1a12657552.png)

Other collider types will show correctly.
Box   Capsule   Sphere
![image](https://user-images.githubusercontent.com/7885830/88171650-affdf300-cc5a-11ea-9253-f8f65b293065.png)

**Comment by willeastcott** [comment]
When you add a capsule collision component, the JS console reports:

```playcanvas-stable.js:52004 Failed to link shader program. Error: Attribute 'aSide' aliases attribute 'aPosition' at location 0```

This is because of this code:

```
        var vertexFormatAttr0 = new pc.VertexFormat(app.graphicsDevice, [
            { semantic: pc.SEMANTIC_POSITION, components: 3, type: pc.ELEMENTTYPE_FLOAT32 },
            { semantic: pc.SEMANTIC_NORMAL, components: 3, type: pc.ELEMENTTYPE_FLOAT32 },
            { semantic: pc.SEMANTIC_ATTR0, components: 1, type: pc.ELEMENTTYPE_FLOAT32 }
        ]);
```

So the position semantic is clashing with `ATTR0` (since the `ATTR*` semantics were recently remapped to specific slots and `ATTR0` and `POSITION` are both 0).

If you search for `SEMANTIC_ATTR` in the Editor source, there are a few occurences. So actually, this same bug also causes a failed shader link for the spotlight gizmo code too.

**Comment by LeXXik** [comment]
Oh, I actually thought it was a feature :) I was creating a vertex format, and it complained about attr0 and position conflict. I just used next available slot. Should have reported. Good to know.

**Comment by mvaligursky** [comment]
This has now been fixed, pending the Editor release. I'll close the issue.
