### ISSUE TITLE
Downloaded build does not save anti-alias setting

### ISSUE THREAD

**Issue by LeXXik** [playcanvas/editor#1125]
Forum: https://forum.playcanvas.com/t/anti-aliasing-always-enabled-in-builds/35298

Running the build locally shows that 4 samples are used by the frame buffer, instead of 1.

**Comment by Sam-RDX** [comment]
Seems to be caused by the generated __settings__.js defining the option `antialias`, while __start__.js will look for a field named `antiAlias` (second A is uppercase) and fallback to true since it can’t find the setting.

Thus all builds will currently have AA enabled independent of what was set in the settings.

Changing either the __settings__.js or the __start__.js manually will fix the issue.
