### ISSUE TITLE
FBX sampling rate expose

### ISSUE THREAD

**Issue by Askhento** [playcanvas/editor#31]
Currently 0.1 sec is sampling resolution, this is not enough for 30 fps animation. It results to a wrong motion of bones.

**Comment by slimbuck** [comment]
We can't simply increase the sampling rate at which animations are converted, because this will cause everyone's animation file size to bloat (in many cases unnecessarily).

In the short term we can perhaps expose the sampling rate to the user, however longer term we need a more efficient animation processing. For example, since we will soon export to GLB format, we can look into exporting cubic curves. (We currently only convert linear segments).

**Comment by Askhento** [comment]
I agree for most cases we don't need that, but when something goes wrong you need a bodge.

Will GLB affect the file size?

**Comment by yaustar** [comment]
This is now exposed in the Editor project settings.

**Comment by willeastcott** [comment]
Yep - pretty sweet!

![image](https://user-images.githubusercontent.com/697563/96867859-25997b00-1465-11eb-96ad-ac4d86271818.png)
