### ISSUE TITLE
Add an option to exclude assets completely from a build

### ISSUE THREAD

**Issue by yaustar** [playcanvas/editor#315]
Currently, we can prevent an asset from being loaded by disabling the preload flag. However, this does not stop it from being published with the build (e.g the file is still accessible if the URL is known).

This ticket is more to gauge the need for something like this where an asset can be completely omitted from the build.

Some examples include being able to add documentation to library folders and example assets/scripts/etc that shouldn't be packaged by projects that use them.

Some of this can be mitigated by branches in version control but it feels a bit of a clumsy workaround. We currently can exclude scenes from builds, it seems to make sense to be able to do the same with assets.

Discuss below :)

**Comment by willeastcott** [comment]
Maybe change the Preload checkbox to a dropdown with options:

* Preload
* Stream
* Exclude

**Comment by yaustar** [comment]
Stream might need to be something else as someone may see it as MP3/MP4 like streaming for example but yeah, a drop down would nice. 'On Demand' instead?

As a related side feature, there have been requests for easy filtering on what is preloaded or not to make managing assets easier on large projects, having this feature would add more for that need

**Comment by Christopher-Hayes** [comment]
Yeah, I have quite a few "original" assets that I don't use and don't want to get rid of in-case I need to recompress, but are included in each build and bloat the amount of data that has to be uploaded to staging. This would be a really nice feature.

**Comment by leonidaspir** [comment]
We have a special use case that can make use of this feature:

- In development we use regular model assets for our model and collision components.
- In production to reduce the number of HTTP requests we bundle in our modelling app those models in a single model asset. When that asset gets uploaded to the editor we use a special editor script to read each mesh instance and pin point where it's being used in the scene (model and collision components).

It would be great if we can exclude from a build the original model assets but at the same time keep them in the project since they are required by our art workflow.

**Comment by davidpox** [comment]
I was going to suggest this too but just saw this! I would love the same kind of option for entities too, as sometimes I back up entities and disable them in case I need them later. But having this for Assets is definitely a wish of mine!

**Comment by yaustar** [comment]
@davidpox You can copy and paste entities between projects and scenes. So you could backup entities in an unused scene in this specific case.

**Comment by yaustar** [comment]
Fixed in v1.19.9
