### ISSUE TITLE
Text files being served as 'text/plain' instead of expected 'text'

### ISSUE THREAD

**Issue by yaustar** [playcanvas/editor#412]
Example project: https://playcanvas.com/project/802245/overview/text-served-incorrectly

![image](https://user-images.githubusercontent.com/16639049/120928247-bd3d9800-c6db-11eb-971b-a9e63fd95b02.png)

Not 100% sure if this is server config issue or an engine issue.

**Comment by vkalpias** [comment]
This is just a log in the engine - it is not a problem other than an unnecessary warning in this case.

**Comment by yaustar** [comment]
Should the warning be wrapped in #debug builds in that case?

**Comment by vfernandestoptal** [comment]
It would be great for us if it didn't show in production builds, since we are sending it to our logs and it becomes noise

**Comment by yaustar** [comment]
Created PR https://github.com/playcanvas/engine/pull/3227

**Comment by 403-Fruit** [comment]
Could this be reconsidered? In some projects it's outputting 50+ warnings for me. Keep in mind that the console is frequently used in debug builds as well. 

![image](https://user-images.githubusercontent.com/46859125/126490920-6f5dfa33-15d8-48cb-99c3-f1c1def3c123.png)

Is there actually any useful information being conveyed to the developer? If not, it would be nice if it could be removed completely. Otherwise it's not a big deal, just a minor annoyance.
