### ISSUE TITLE
Show a modal in the Editor on new Engine and Editor releases

### ISSUE THREAD

**Issue by yaustar** [playcanvas/editor#428]

**Comment by Maksims** [comment]
Showing a modal - would be too much. Not sure everyone really ** has to know** about updates. Some definitely would want to know about it, but it is their decision to find out. Adding extra clicks before they can work - is not nice.

A button on the left panel with "Change Log", that brings info about Editor and Engine changes - would be great.
And it can be highlighted if the editor/engine has been updated since previous visits, with a small tooltip shown when entering editor if there were changes since the last visit of the editor, which would hide on delay.

It would be "marked" as not highlighted after the first time seen, without a need to click on it. As many users just will not.

When clicked, it should remember what versions been seen before, and mark a list of versions since then, so the viewer can know what has been added since this modal window has been seen.

So from data, you would need to have:
1. Global values of the latest version of the editor and engine.
2. User scope values of the last **seen** editor and engine versions. This updates every time editor is opened.
3. User scope values of the last **read** editor and engine versions. This is updated every time the change-log modal is opened.

**Comment by willeastcott** [comment]
We now have the WHAT'S NEW button when the Editor is updated.

![image](https://user-images.githubusercontent.com/697563/221356366-72268c13-3b52-4547-a0fa-4759cc332e47.png)

Closing.
