### ISSUE TITLE
Textures on meshes in Particle Systems no longer fit after engine change

### ISSUE THREAD

**Issue by h0lmiew** [playcanvas/editor#490]
### Description

After the engine changes that required recompressing textures with inverted uv coordinates, textures applied to meshes in particle system not longer looks correct.

![image](https://user-images.githubusercontent.com/5739868/128717303-0826ff4a-a347-49e8-b8f2-5a18c5cd9b66.png)

Previously our fired shells would be yellow, but now they are white.

Test project with just our particle system and model mesh + texture can be seen here:
https://playcanvas.com/editor/scene/1187304

### Steps to Reproduce

1. Open play mode of test project
2. See that fired shells are white
3. They should have been golden

Is it possible the particle system internally has not been updated to reflect inverted uv coordinates in textures?

**Comment by slimbuck** [comment]
Hi @h0lmiew,

Thanks so much for reporting this issue and supplying a repo. Will look into this ASAP!

**Comment by willeastcott** [comment]
Fixed in https://github.com/playcanvas/engine/pull/3384 which will be deployed to production in the second half of this week.

**Comment by h0lmiew** [comment]
Hey @willeastcott - is this released now? We are still seeing the issue, which unfortunately is keeping us from being able to do a new release of our game. 

Regards, Lars

**Comment by willeastcott** [comment]
Last week's release was delayed in order to complete a refactor of the StandardMaterial shader code: https://github.com/playcanvas/engine/pull/3391

Now that that is done, we are implementing support for general-purpose texture transforms today. We'll then test tomorrow and release should go ahead on Monday.

If you need to release before then, one option is swap your published project's engine with:

https://code.playcanvas.com/playcanvas-latest.js

That is the latest build of the master branch that includes the fix.

**Comment by willeastcott** [comment]
[Engine 1.46.0](https://github.com/playcanvas/engine/releases/tag/v1.46.0) was just deployed. Thanks for your patience!
