### ISSUE TITLE
Texture Atlases that are compressed with Basis still package the original jpg/png when publishing

### ISSUE THREAD

**Issue by yaustar** [playcanvas/editor#694]
Repro: https://playcanvas.com/project/884322

<img width="330" alt="image" src="https://user-images.githubusercontent.com/16639049/154492721-15c41a1c-32ca-4b70-881c-fe3853705b29.png">

<img width="535" alt="image" src="https://user-images.githubusercontent.com/16639049/154492828-1d2868ce-7640-4336-a94a-818efa7615aa.png">

**Comment by yaustar** [comment]
> Is there a case where basis texture is not loadable?

Shouldn't be, no. The idea is that basis library is always available and will always transcode to an available format

**Comment by Maksims** [comment]
Then, I believe it is due to previous texture variants mechanics. Legacy compression used to allow developer to compress to specific formats, which did not guarantee 100% coverage of all platforms, so appropriate compressed variant would load, and if none supported, would fallback to uncompressed png/jpeg, that is why it was packaging compressed with uncompressed.

If Basis 100% guarantees coverage, and is always shipped (not able to turn off by code), then it probably should not package png/jpeg in an export then.

There will be probably few edge cases of project setup: with basis compressed texture, but basis library removed from the project - in this case it should package original png/jpeg.
Also, is it possible to mix legacy with basis? There will be edge cases there too.

**Comment by yaustar** [comment]
Bumped the priority as this is affecting preload bundle sizes for Snapchat Games

**Comment by yaustar** [comment]
Fixed in release of v1.21.61 that we are aiming to release on Monday/Tuesday
