### ISSUE TITLE
Anim Mask don't work

### ISSUE THREAD

**Issue by Maksims** [playcanvas/editor#724]
Been fighting with Animation Masks for some time, and am unable to make them work in Editor.

If no Mask is created, it works as expected, two Layers can blend as expected. But once layer Mask is defined for the Top layer (upper body), then it just gets ignored.

Here is an example project: https://playcanvas.com/project/900875/overview/anim-mask-issues

There are two entities, with the same animation graph. "Character Masked" entity has a mask defined for the Top layer, that selects only upper body bones.

# Issue:

The Top layer is completely ignored when Mask is defined.

# Expectations:

Upper body to work as expected, and simply override animation. So character will be playing punching animation with the upper body while running with the lower body.

P.S. tutorial projects to cover as many animation features covered (small project per feature) would be highly appreciated.

**Comment by yaustar** [comment]
This is a massively delayed reply and more posting about this for information than anything else.

The issue is that the mask hierarchy didn't match up exactly to what the animation paths were looking for

'Character Masked' had the anim component with the Root Bone as 'root' child entity
<img width="531" alt="image" src="https://user-images.githubusercontent.com/16639049/205891044-25df71e3-08a8-4894-aa84-e201371b95a4.png">

However, the animations have the following:
<img width="290" alt="image" src="https://user-images.githubusercontent.com/16639049/205891143-a86dfcde-9d1c-460d-a71a-568a6d5ddbc6.png">

The 'root' entity is expected to be under the Root Bone

So changing the Root Bone on the Anim Component to be the 'Character Masked' entity (parent of the 'root' entity) and updating the mask on the layer
<img width="519" alt="image" src="https://user-images.githubusercontent.com/16639049/205891432-bfb504cd-58ac-4bb3-bf0b-d1fb068cc405.png">

Fixes the issue where the mask path matches the animation path.

https://user-images.githubusercontent.com/16639049/205891685-45247c89-5def-4200-821a-a234b4075abd.mp4

Project: https://playcanvas.com/project/1016269
