### ISSUE TITLE
Material selection UI and UX improvement

### ISSUE THREAD

**Issue by jiajasper** [playcanvas/editor#734]
The current material selection (under render component) has the following UX/UI issues:

1. In empty state, there should only be one CTA which is to add a material to the empty slot, but we have two icons - "edit" and "cross" - which are not semiotically accurate and not relevant in empty state. -**> Suggest having only one "plus" icon to prompt users add a material to the slot.**
2. Array size is read only - we currently use an input component to host this information which can be confusing because user would think they that the array size is editable through UI. **-> Suggest presenting this number in a bracket behind "Material"to indicate the number of materials referenced.**

![image](https://user-images.githubusercontent.com/30747200/161572639-f4031a62-513d-47d5-9e01-0842d4f626b2.png)

3. Once the material slot is in selecting state, it is not clear that what the next step is if there there is no materials found in the current directory. **-> Suggest to add a line of copy to clearly indicate the empty state and also add a "create material"button to prompt the user to create a new material. Further, in selecting state, along with highlighting the asset panel, we would also highlight the material slot that we are selecting material.**

![image](https://user-images.githubusercontent.com/30747200/161572152-a0f2b62f-d877-4c9e-966d-81564edf4bf5.png)

4. Material inspector menu information architecture is a bit chaotic - having two collapsible shelves called "Material"on the same panel. **-> For a quick clean up, suggest to move shading setting and download into the preview panel and merge the metadata into a collapsible shelf.**

![image](https://user-images.githubusercontent.com/30747200/161573423-dd43a1f1-e31b-45d1-a8b7-67b1f5632675.png)

**Comment by Maksims** [comment]
Asset picker definitely can receive some love.

> ![image](https://user-images.githubusercontent.com/30747200/161572639-f4031a62-513d-47d5-9e01-0842d4f626b2.png)

This is a better placement compared to the current edit and X buttons, just take into account that the slot name can be long enough, and needs to be overflown using CSS.
**Darker block** - helps to separate blocks, but, it goes against the common language of the way that color is currently used: any dark block - is clickable/interactive. For that reason, I've previously put interactive icons on a field, otherwise, without block separation, it is hard to understand to which element those icons belong.
Also, using a bucket - will be less appropriate here, as it feels like "deleting a slot" instead of "removing an asset from a slot".

**Bucket icon** - leads to deletion of an element/slot/whatever.
**Cross icon** - leads to clearing an element/slot/whatever.

**Shading on material** - could be just below "Created". It is not a preview setting, but the shading model that is used to calculate specularity. I gues worth talking about deprecating old shading model by now, if it is ever used anywhere?

**Comment by jiajasper** [comment]
@Maksims Hey Max! All valid points there! Would use these design as a starting point to start revamping some of the UX logics behind all **Assets** related components and flows.

**Comment by yaustar** [comment]
Please split into separate tickets where the changes proposed here will need to be across all assets, not just material

**Comment by jiajasper** [comment]
After discussion, for this ticket, we are changing the array size input box to read only.

For the rest, I will be making them into a new ticket for review.
