### ISSUE TITLE
Importing a 200+MB FBX will not succeed and give 504 error

### ISSUE THREAD

**Issue by yaustar** [playcanvas/editor#809]
// Martin to add FBX

**Comment by mvaligursky** [comment]
A little bit after I got this error, the import seems to have finished just fine, and I can use the created template.

**Comment by willeastcott** [comment]
This seems to import fine for me now:

![image](https://user-images.githubusercontent.com/697563/221359368-1e225a68-77ff-4de5-8228-949935850fff.png)

But it takes about 5 minutes to import and then another few minutes to instantiate in the viewport. The META stats say it has about 0.8 billion vertices. It may be possible that redundant vertices are being generated in the import process, but since this does actually import OK, I'm closing.
