### ISSUE TITLE
Visualize tiling and offset of texture

### ISSUE THREAD

**Issue by marcusx2** [playcanvas/editor#884]
https://user-images.githubusercontent.com/5656275/190918280-cabea9dd-fad5-4a24-8d8e-3a58d66054b6.mp4

**Comment by willeastcott** [comment]
I'm not convinced this is necessary. Since you can see realtime updates of changes to the texture transform in the viewport and the launch page, having a separate view won't buy you much.

I have a feeling that you used to be able to switch the sphere in the Material Inspector to other shapes (like a cube). But that functionality doesn't seem to exist any more. This was maybe lost when we switched to the new Material Inspector around 2 or 3 years ago. But yeah, if we brought that back, you'd also see the material on the side of a cube (or even a plane) which would be similar.

**Comment by willeastcott** [comment]
Yes, by viewport, I mean the 3D View in the Editor. The changes are definitely reflected there in realtime as you adjust values. Since you agree, I'll go ahead and close this. 😄
