### ISSUE TITLE
Resize Image Element to Sprite Dimensions

### ISSUE THREAD

**Issue by SophieRefshauge** [playcanvas/editor#9]
Sprites have a standard size of 32x32 when added to the scene as UI elements.
Instead, I would expect them to be created at their original sprite dimension (same behaviour as when you create a sprite in world).

https://playcanvas.com/editor/scene/875325

**Comment by halvves** [comment]
Sorry it has taken me a bit to get back to this one.

The behavior you are seeing here is likely due to the difference between "world" units and "screen space" units. Sprite Assets have a property called [Pixels Per Unit](https://developer.playcanvas.com/en/user-manual/assets/sprites/#pixels-per-unit). I'm assuming your Sprite asset has a Pixels Per Unit of `100` (the usual default for sprites), and thus appears very small in screen space (100 sprite pixels per screen pixel/unit). The best practice here is to set Pixels Per Unit to `1` for usage within screen space (1 sprite pixel per screen pixel/unit).

Let me know if this clears things up, or if there are still issues.

**Comment by SophieRefshauge** [comment]
Hi @halvves ,
I'm not sure this is the issue.
We have to set sprites to 100 if regular and 1 if sliced. This seems to be the only way to make them behave as expected. (I mostly use image elements in screenspace).
If i want the image element to be created with the original dimension, I have to go into the sprite sheet, find the right frame, write down the size and manually type them into the image elements width and height - because all image elements are initially created as 32x32 when you plop in a sprite element.
When creating a sprite with a Pixel Per Unit of 100 in the root, it knows its own original size/ratio, and there's no need for manual size setting.
I'd love for the image element to resize itself to the original size/ratio when a sprite element is plotted into and image element. **Even better: have a button to click "resize to original scale" when you want it to do it.**

Does this make any sense?

![SpriteSize_differenceBtwSpriteAndImageElement](https://user-images.githubusercontent.com/61006029/77152306-f9191d00-6a97-11ea-941e-646d283db518.jpg)

**Comment by halvves** [comment]
Ah yes. Ok. Terribly sorry I misunderstood your first message. This is definitely something we can do!

**Comment by SophieRefshauge** [comment]
No worries. Looking forward to this implementation :)

**Comment by yaustar** [comment]
Feature related to https://github.com/playcanvas/editor/issues/111

**Comment by yaustar** [comment]
> If i want the image element to be created with the original dimension, I have to go into the sprite sheet, find the right frame, write down the size and manually type them into the image elements width and height - because all image elements are initially created as 32x32 when you plop in a sprite element.

This is now implemented :)
